---
  - name: add nginx official repo apt list file
    template: src=nginx.list.j2 dest=/etc/apt/sources.list.d/nginx.list mode=0644
    register: official_repo_added
    when: nginx_custom != True

  - name: Add nginx official repo key
    apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
    when: official_repo_added.changed and nginx_custom != True

  - name: Add jessie-backports for Debian
    template:
      src: jessie-backports.list.j2
      dest: /etc/apt/sources.list.d/jessie-backports.list
      mode: 0644
    when: ansible_distribution == 'Debian'

  - name: Update apt cache
    apt: update_cache=yes
    when: official_repo_added.changed

  - name: Ensure openssl is installed
    apt:
      name: openssl
      force: yes
      state: latest
      default_release: jessie-backports
    when: ansible_distribution == 'Debian'

  - name: Ensure nginx is installed
    apt:
      name: nginx
    when: nginx_custom != True

  - name: Install custom
    shell: dpkg -i {{ nginx_custom_path }}/{{ item }}
    with_items: "{{ nginx_custom_debs }}"
    when: nginx_custom is defined and nginx_custom
    ignore_errors: yes

  - name: Install custom dependencies
    command: apt-get install -fy
    when: nginx_custom is defined and nginx_custom

  - name: Remove default configuration
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "/etc/nginx/sites-enabled/default"
      - "/etc/nginx/sites-available/default"
      - "/etc/nginx/conf.d/default.conf"

  - name: Write nginx.conf
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify:
      - validate nginx configuration
      - restart nginx

  - name: Rsync files
    synchronize:
      src: files/nginx-conf/
      dest: /etc/nginx/conf.d
      rsync_opts: '--no-owner --no-group'
    notify:
      - validate nginx configuration
      - restart nginx

  - name: Create dhparam
    command: openssl dhparam -out {{nginx_dhparam_path}} {{nginx_dhparam_encryption_size}}
    args:
      creates: "{{nginx_dhparam_path}}"
    when: nginx_dhparam_path is defined and nginx_dhparam_path
    notify:
      - validate nginx configuration
      - restart nginx

  - name: Ensure nginx is started and enabled to start at boot.
    service: name=nginx state=started enabled=yes
